runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
  http_headers:
    Access-Control-Allow-Origin: "*"
  expiration: "0s"

- url: /(.*)
  static_files: \1
  upload: (.*)
  expiration: "0s"
